#!/bin/sh

case $1 in
    start)
        if ! systemctl start $2 >/dev/null 2>/dev/null; then
            echo "Failed to start"
            exit 1
        fi
    ;;
    stop)
        if ! systemctl stop $2 >/dev/null 2>/dev/null; then
            echo "Failed to stop"
            exit 1
        fi
    ;;
    restart)
        if ! systemctl restart $2 >/dev/null 2>/dev/null; then
            echo "Failed to restart"
            exit 1
        fi
    ;;
    reload)
        if ! systemctl reload $2 >/dev/null 2>/dev/null; then
            echo "Failed to reload"
            exit 1
        fi
    ;;
    status)
        if systemctl is-active $2 >/dev/null 2>/dev/null; then
            echo "Running"
        else
            echo "Not Running"
            exit 1
        fi
    ;;
    reload-configuration)
        if ! systemctl daemon-reload >/dev/null 2>/dev/null; then
            echo "Failed to reload configuration"
            exit 1
        fi
    ;;
    enable)
    	if ! systemctl enable $2 >/dev/null 2>/dev/null; then
            echo "Failed to enable"
            exit 1
        fi
    ;;
    disable)
    	if ! systemctl disable $2 >/dev/null 2>/dev/null; then
            echo "Failed to disable"
            exit 1
        fi
    ;;
    *)
        echo "Usage: `basename "$0"` {start|stop|status|restart|reload|reload-configuration|enable|disable} <service>"
        exit 1
    ;;
esac

exit 0